# Generated by Django 6.0.5 on 2026-06-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='proyectos/portadas/', verbose_name='Imagen de portada'),
        ),
    ]
