# Generated by Django 6.0.5 on 2026-06-17 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_proyecto_imagen_portada'),
        ('usuarios', '0003_fix_cedulas_start_with_11'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='estrategias_ejecucion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='proyectos/anexos/')),
                ('tipo', models.CharField(choices=[('CONVENIO', 'Convenio'), ('RESOLUCION', 'Resolución'), ('CARTA', 'Carta de compromiso'), ('AVANCE', 'Informe de avance'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='proyectos.proyecto')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexos_subidos', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
                'ordering': ['proyecto', 'orden', '-creado_en'],
            },
        ),
    ]
