# Generated by Django 6.0.5 on 2026-06-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_proyecto_imagen_portada'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatoInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
                ('nivel', models.CharField(choices=[('PREGRADO', 'Pregrado'), ('POSGRADO', 'Posgrado')], max_length=20)),
                ('tipo', models.CharField(choices=[('GUIA', 'Guia metodologica'), ('FORMULACION', 'Formato Formulacion'), ('AVANCE', 'Informe de Avance'), ('FINAL', 'Informe Final')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(upload_to='formatos/')),
                ('tamano_kb', models.CharField(blank=True, max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Formato institucional',
                'verbose_name_plural': 'Formatos institucionales',
                'ordering': ['nivel', 'tipo', '-creado_en'],
            },
        ),
    ]
