# Generated by Django 6.0.5 on 2026-06-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_formatoinstitucional'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='beneficiarios_directos',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='beneficiarios_indirectos',
            field=models.TextField(blank=True, default=''),
        ),
    ]
