# Generated by Django 6.0.5 on 2026-06-20 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_proyecto_estrategias_ejecucion_anexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alineacionestrategica',
            name='agenda_zonal',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Agenda zonal'),
        ),
        migrations.AddField(
            model_name='alineacionestrategica',
            name='eje_plan_igualdad',
            field=models.CharField(blank=True, choices=[('GENERO', 'Genero'), ('PUEBLOS', 'Pueblos y nacionalidades'), ('DISCAPACIDADES', 'Discapacidades'), ('SOCIOECONOMICA', 'Condicion socioeconomica'), ('NO_APLICA', 'No aplica')], default='', max_length=50, verbose_name='Eje del Plan de Igualdad'),
        ),
        migrations.AddField(
            model_name='alineacionestrategica',
            name='linea_investigacion',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Linea de investigacion'),
        ),
        migrations.AddField(
            model_name='alineacionestrategica',
            name='ods',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ODS'),
        ),
        migrations.AddField(
            model_name='alineacionestrategica',
            name='plan_nacional_desarrollo',
            field=models.TextField(blank=True, default='', verbose_name='Plan Nacional de Desarrollo'),
        ),
        migrations.AddField(
            model_name='alineacionestrategica',
            name='programa_vinculacion',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Programa de vinculacion'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='monto_externo_economico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto externo economico'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='monto_externo_valorado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto externo valorado'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='monto_unl_economico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto UNL economico'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='monto_unl_valorado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto UNL valorado'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='seguimiento_evaluacion',
            field=models.TextField(blank=True, default='', verbose_name='Seguimiento y evaluacion'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='viabilidad',
            field=models.TextField(blank=True, default='', verbose_name='Viabilidad del proyecto'),
        ),
        migrations.CreateModel(
            name='MarcoLogicoFila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nivel', models.CharField(choices=[('FIN', 'Fin (Objetivo de Desarrollo)'), ('PROPOSITO', 'Proposito (Objetivo General)'), ('COMPONENTES', 'Componentes (Objetivos Especificos)'), ('ACTIVIDADES', 'Actividades Principales')], max_length=20)),
                ('resumen_narrativo', models.TextField(blank=True, default='')),
                ('indicadores', models.TextField(blank=True, default='')),
                ('medios_verificacion', models.TextField(blank=True, default='')),
                ('supuestos', models.TextField(blank=True, default='')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marco_logico', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Fila de marco logico',
                'verbose_name_plural': 'Filas de marco logico',
                'ordering': ['nivel'],
                'unique_together': {('proyecto', 'nivel')},
            },
        ),
    ]
