# Generated by Django 6.0.5 on 2026-06-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_alineacionestrategica_agenda_zonal_and_more'),
        ('usuarios', '0004_usuario_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='carreras',
            field=models.ManyToManyField(blank=True, related_name='proyectos_multiples', to='usuarios.carrera'),
        ),
    ]
