# Generated by Django 6.0.5 on 2026-05-12 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
                ('sigla', models.CharField(blank=True, default='', max_length=50)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('sitio_web', models.URLField(blank=True, default='')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Institucion',
                'verbose_name_plural': 'Instituciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('entidad_contraparte', models.CharField(max_length=255)),
                ('objeto', models.TextField()),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_firma', models.DateField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('MARCO', 'Marco'), ('ESPECIFICO', 'Especifico'), ('COOPERACION', 'Cooperacion'), ('OTRO', 'Otro')], default='ESPECIFICO', max_length=20)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En revision'), ('VIGENTE', 'Vigente'), ('VENCIDO', 'Vencido'), ('SUSPENDIDO', 'Suspendido'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=20)),
                ('archivo_firmado', models.FileField(blank=True, null=True, upload_to='convenios/')),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('institucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convenios', to='convenios.institucion')),
            ],
            options={
                'verbose_name': 'Convenio',
                'verbose_name_plural': 'Convenios',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Contribucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('FINANCIERO', 'Financiero'), ('HORAS', 'Horas'), ('INFRAESTRUCTURA', 'Infraestructura'), ('EQUIPO', 'Equipo'), ('SERVICIO', 'Servicio'), ('EXTERNO', 'Externo')], default='FINANCIERO', max_length=20)),
                ('descripcion', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_aporte', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribuciones', to='proyectos.proyecto')),
                ('institucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribuciones', to='convenios.institucion')),
            ],
            options={
                'verbose_name': 'Contribucion',
                'verbose_name_plural': 'Contribuciones',
                'ordering': ['proyecto', '-fecha_aporte'],
            },
        ),
        migrations.CreateModel(
            name='Compromiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=40)),
                ('descripcion', models.TextField()),
                ('fecha_compromiso', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('CUMPLIDO', 'Cumplido'), ('INCUMPLIDO', 'Incumplido')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compromisos_responsables', to='usuarios.usuario')),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compromisos', to='convenios.convenio')),
            ],
            options={
                'verbose_name': 'Compromiso',
                'verbose_name_plural': 'Compromisos',
                'ordering': ['convenio', 'fecha_vencimiento'],
                'unique_together': {('convenio', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(blank=True, max_length=50)),
                ('fecha_entrega_esperada', models.DateField(blank=True, null=True)),
                ('fecha_entrega_real', models.DateField(blank=True, null=True)),
                ('entregado', models.BooleanField(default=False)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='productos/')),
                ('observaciones', models.TextField(blank=True)),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='convenios.convenio')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['convenio', 'fecha_entrega_esperada'],
                'unique_together': {('convenio', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='ProyectoConvenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha_vinculacion', models.DateField(auto_now_add=True)),
                ('vigente', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculaciones_proyecto', to='convenios.convenio')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculaciones_convenio', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Vinculacion proyecto-convenio',
                'verbose_name_plural': 'Vinculaciones proyecto-convenio',
                'ordering': ['-creado_en'],
                'unique_together': {('proyecto', 'convenio')},
            },
        ),
    ]
