# Generated by Django 6.0.5 on 2026-06-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenio',
            name='codigo',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
    ]
