# Generated by Django 6.0.5 on 2026-05-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='detalle',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
