# Generated by Django 6.0.5 on 2026-06-20 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_fix_cedulas_start_with_11'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cargo'),
        ),
    ]
