export const API_BASE = import.meta.env.VITE_API_URL || '/api/v1'

export const API = {
  AUTH: {
    LOGIN: '/auth/login/',
    REGISTER: '/auth/register/',
    REFRESH: '/auth/refresh/',
  },
  USUARIOS: {
    LIST: '/usuarios/',
    DETAIL: (id: number) => `/usuarios/${id}/`,
    ME: '/usuarios/me/',
    CARRERAS: '/carreras/',
    CAMBIAR_ROL: (id: number) => `/usuarios/${id}/`,
  },
  PROYECTOS: {
    LIST: '/proyectos/',
    DETAIL: (id: number) => `/proyectos/${id}/`,
    ENVIAR_REVISION: (id: number) => `/proyectos/${id}/enviar-revision/`,
    APROBAR: (id: number) => `/proyectos/${id}/aprobar/`,
    RECHAZAR: (id: number) => `/proyectos/${id}/rechazar/`,
    INICIAR_EJECUCION: (id: number) => `/proyectos/${id}/iniciar-ejecucion/`,
    SUSPENDER: (id: number) => `/proyectos/${id}/suspender/`,
    REANUDAR: (id: number) => `/proyectos/${id}/reanudar/`,
    FINALIZAR: (id: number) => `/proyectos/${id}/finalizar/`,
    CERRAR: (id: number) => `/proyectos/${id}/cerrar/`,
    CANCELAR: (id: number) => `/proyectos/${id}/cancelar/`,
    OBJETIVOS: '/objetivos/',
    OBJETIVOS_BY_PROYECTO: (id: number) => `/objetivos/?proyecto=${id}`,
    INDICADORES: '/indicadores/',
    INDICADORES_BY_PROYECTO: (id: number) => `/indicadores/?proyecto=${id}`,
    ACTIVIDADES: '/actividades/',
    ACTIVIDADES_BY_PROYECTO: (id: number) => `/actividades/?proyecto=${id}`,
    PARTICIPANTES: '/participantes/',
    PARTICIPANTES_BY_PROYECTO: (id: number) => `/participantes/?proyecto=${id}`,
    PRESUPUESTOS: '/presupuestos/',
    BENEFICIARIOS: '/beneficiarios/',
    ALINEACIONES: '/alineaciones/',
    FIRMAS: '/firmas/',
  },
  CONVENIOS: {
    LIST: '/convenios/',
    DETAIL: (id: number) => `/convenios/${id}/`,
    SIGUIENTE_CODIGO: '/convenios/siguiente-codigo/',
    ENVIAR_REVISION: (id: number) => `/convenios/${id}/enviar-revision/`,
    APROBAR: (id: number) => `/convenios/${id}/aprobar/`,
    RECHAZAR: (id: number) => `/convenios/${id}/rechazar/`,
    SUSPENDER: (id: number) => `/convenios/${id}/suspender/`,
    FINALIZAR: (id: number) => `/convenios/${id}/finalizar/`,
    CANCELAR: (id: number) => `/convenios/${id}/cancelar/`,
    COMPROMISOS: '/compromisos/',
    COMPROMISOS_BY_CONVENIO: (id: number) => `/compromisos/?convenio=${id}`,
    PRODUCTOS: '/productos/',
    PRODUCTOS_BY_CONVENIO: (id: number) => `/productos/?convenio=${id}`,
    PROYECTO_CONVENIOS: '/proyecto-convenios/',
    CONTRIBUCIONES: '/contribuciones/',
  },
  INSTITUCIONES: {
    LIST: '/instituciones/',
    DETAIL: (id: number) => `/instituciones/${id}/`,
  },
  SEGUIMIENTO: {
    AVANCES: {
      LIST: '/avances/',
      DETAIL: (id: number) => `/avances/${id}/`,
      BY_ACTIVIDAD: (id: number) => `/avances/?actividad=${id}`,
      APROBAR: (id: number) => `/avances/${id}/aprobar/`,
      RECHAZAR: (id: number) => `/avances/${id}/rechazar/`,
    },
    EVIDENCIAS: {
      LIST: '/evidencias/',
      DETAIL: (id: number) => `/evidencias/${id}/`,
      BY_AVANCE: (id: number) => `/evidencias/?avance=${id}`,
      BY_ACTIVIDAD: (id: number) => `/evidencias/?actividad=${id}`,
    },
    INFORMES: {
      LIST: '/informes/',
      BY_PROYECTO: (id: number) => `/informes/?proyecto=${id}`,
      DETAIL: (id: number) => `/informes/${id}/`,
    },
    ALERTAS: {
      LIST: '/alertas/',
      BY_USUARIO: (id: number) => `/alertas/?usuario=${id}`,
      PENDIENTES: '/alertas/?estado=PENDIENTE&leida=false',
      DETAIL: (id: number) => `/alertas/${id}/`,
      LEER: (id: number) => `/alertas/${id}/leer/`,
      ATENDER: (id: number) => `/alertas/${id}/atender/`,
    },
    REVISIONES: {
      LIST: '/revisiones/',
    },
    FLUJOS_VALIDACION: {
      LIST: '/flujos-validacion/',
    },
  },
  REPORTES: {
    DASHBOARD: '/reportes/dashboard/',
    PROYECTOS: '/reportes/proyectos/',
    CONVENIOS: '/reportes/convenios/',
    PROGRESO: '/reportes/progreso/',
  },
  FORMATOS: {
    LIST: '/formatos/',
    DETAIL: (id: number) => `/formatos/${id}/`,
  },
  AUDITORIA: {
    LIST: '/auditoria/registros/',
  },
} as const
