# Generated by Django 6.0.7 on 2026-07-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avance',
            name='motivo_rechazo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
