# Generated by Django 6.0.5 on 2026-06-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormatoInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('nivel', models.CharField(choices=[('PREGRADO', 'Pregrado'), ('POSGRADO', 'Posgrado')], max_length=20)),
                ('tipo', models.CharField(choices=[('GUIA', 'Guía metodológica'), ('FORMULACION', 'Formato de formulación'), ('AVANCE', 'Informe de avance'), ('FINAL', 'Informe final')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(upload_to='formatos/%Y/%m/')),
                ('tamano_kb', models.PositiveIntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Formato Institucional',
                'verbose_name_plural': 'Formatos Institucionales',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
    ]
